spring:
    datasource:
        url: jdbc:postgresql://grvdbinstance.cql8xnmimrct.us-west-1.rds.amazonaws.com:5432/grv
        username: usernamegrv
        password: passwordgrv
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
server:
    port: 8455
        